micronaut:
  application:
    name: micronaut-workshop-baseline

netty:
  default:
    allocator:
      max-order: 3

endpoints:
  info:
    sensitive: false
  health:
    details-visible: anonymous
    disk-space:
      enabled: false